variables:
  GIT_SSL_NO_VERIFY: "true"

build:
  tags:
    - python3
  script:
    - virtualenv -p python3 env
    - source env/bin/activate
    - python ./setup.py bdist_wheel
  artifacts:
    paths:
      - dist
  only:
    - master
